---
title: "Pilot: Testing CC vs. SE using a probabilistic test query"
author: "Simon Stephan"
output: html_document
---

```{r setup, include=FALSE}
# packages
library(ez)
library(reshape2)
library(reshape)
library(ggplot2)
library(plyr)
library(pastecs)
library(ez)
library(data.table)
#library(Rcmdr)
#Commander()

library(showtext)

font_add_google("Poppins", "Poppins")
font_add_google("Roboto Mono", "Roboto Mono")
showtext_auto()

##########################################Data Managment############################
# read in the data file 

#tdata.wide <- read.delim("dummy_data.txt", header=TRUE, sep="\t", na.strings="NA", dec=".", strip.white=TRUE)
tdata <- read.delim("Data_Exp_CC_vs_SE_ProbQuery_Pilot.txt", header=TRUE, sep="\t", na.strings="NA", dec=".", strip.white=TRUE)

```




# Results 

## Demographics

```{r}
# demographics 
min(tdata$Age)
max(tdata$Age)
mean(tdata$Age)
sd(tdata$Age)

# 1 = male, 2 = female, 3 = other
table(tdata$Sex)
```
1 = male, 2 = female

```{r, echo = FALSE}
# reorder factor 
tdata$type_effect <- factor(tdata$type_effect, levels = c("similar", "diverse"), 
                          labels = c("same domain", "different domains"))

# reorder factor 
tdata$multipotential_cause <- factor(tdata$multipotential_cause, levels = c("blue", "red"), 
                            labels = c("blue crystal", "red crystal"))

# reorder factor 
tdata$target_effect <- factor(tdata$target_effect, levels = c("first", "second", "third"), 
                                     labels = c("first", "second", "third"))


# to create chart, the data must be in long format and only contain the relevant dependent variables

# 1. make a subset with only the relevant dvs 

tdata_sub <- subset(tdata, select = 1:6)


# 2. reshape into long format 
tdata_sub <- melt(tdata_sub, id=c("sID", "type_effect", "multipotential_cause", "target_effect"))


tdata_sub$variable <- factor(tdata_sub$variable, levels = c("single_strength", "multi_strength"), 
                          labels = c("single-effect cause", "multiple-effects cause"))


# recode dependent variables 

tdata_sub$value <- (tdata_sub$value - 1) * 0.1
```

# Graphs

```{r, echo = FALSE}
myTheme <- theme(plot.title = element_text(face="bold", size = 22),
        axis.title.x = element_text(face = "bold", size = 20),
        axis.title.y = element_text(face = "bold", size = 20),
        axis.text.x = element_text(size = 18, angle = 0), 
        axis.text.y = element_text(size = 14, angle = 0),
        legend.text = element_text(size = 18),
        legend.title = element_text(face = "bold", size = 18),
        strip.text.x = element_text(size = 18),
        #panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line.x = element_line(colour = "black"), 
        axis.line.y = element_line(colour = "black"),
        axis.text = element_text(colour ="black"), 
        axis.ticks = element_line(colour ="black"))


library(see)
## first, turn sID into a factor
tdata_sub$sID <- factor(tdata_sub$sID)

pd <- position_dodge(width = 0.3)

tdata_sub$valueJitter <- jitter(tdata_sub$value, factor = 1, amount = 0.04)

theme_set(theme_light(base_size = 20, base_family = "Poppins"))

# new labes for the facets 
effects.labs <- c("Multiple effects from same domain", "Multiple effects from different domains")
names(effects.labs) <- c("same domain", "different domains")

g <- ggplot(tdata_sub, aes(x=variable, y=valueJitter, group = sID)) +
  guides(fill=FALSE)+
  facet_grid( ~ type_effect, labeller = labeller(type_effect = effects.labs))+
  #ggtitle("Subjects' causal srength ratings") +
  scale_y_continuous(limits = c(-0.05, 1.05), breaks=seq(0, 1, 0.1), expand = c(0,0)) +
  scale_x_discrete(labels=c("Single-effect \n cause", "Multiple-effects \n cause")) +
  #stat_summary(fun.y = mean, geom = "bar", position = "dodge", colour = "black", alpha =0.5) +
  geom_violinhalf(aes(y = value, group = variable, fill = variable), color = NA, position=position_dodge(1), alpha = 0.2)+
  geom_line(position = pd, color = "black", size = 1, alpha=0.04) +
  geom_point(aes(color = variable), position = pd, alpha = 0.2) +
  stat_summary(aes(y = value,group=1), fun.data = mean_cl_boot, geom = "errorbar", width = 0, size = 1) +
  stat_summary(aes(y = value,group=1), fun.y=mean, colour="black", geom="line",group=1, size = 1.5, linetype = "solid", alpha = 1)+
  stat_summary(aes(y = value,group=1, fill = variable), fun.y=mean, geom="point", color = "black", shape = 22, size = 5, group=1, alpha = 1)+
  stat_summary(aes(y = value,group=1), fun.y=median, geom="point", color = "black", shape = 3, size = 4, group=1, alpha = 1, position = position_dodge(width = 0.5))+
  labs(x = "Entity", y = "Causal Strength Rating") +
  scale_color_manual(name = "Entity",values=c("#fc9272", "#3182bd"))+
  scale_fill_manual(name = "Entity",values=c("#fc9272", "#3182bd"))+
  theme(legend.position = "none")+
  myTheme
g


#ggsave("results_lines.svg",width=11.5,height=6)
#ggsave("results_lines.pdf",width=11.5,height=6)
```

It can be seen that single-effect causes were perceived to be stronger than multi-effect causes. Whether multi-effect causes produced diverse or very similar effect did not affect their perceived causal strength.



# Descriptive Stats

```{r, echo = FALSE, warning = FALSE, message = FALSE}

################################################################################################################
##################################### Statistical Analyses #####################################################
################################################################################################################
library(pastecs)
library(lme4)
library(nlme)
library(ez)


##################################### Create descriptive stats ###################################

by(tdata_sub$value, list(tdata_sub$variable, tdata_sub$type_effect), stat.desc , basic = FALSE)

##################################### Model ######################################################
```

```{r}
# get the correlation between subjects' two ratings in the different conditions
dat_sameEffects <- subset(tdata, type_effect == "same domain")
dat_diffEffects <- subset(tdata, type_effect == "different domains")



cor.test(dat_sameEffects$multi_strength, dat_sameEffects$single_strength)

cor.test(dat_diffEffects$multi_strength, dat_diffEffects$single_strength)
```




```{r}
library(afex)
library(emmeans)

a1 <- aov_car(value ~ type_effect*variable + Error(sID/(variable)), tdata_sub)
a1
```


```{r}
# same ANOVA as before
lmeModel <- lmer(value ~ type_effect*variable + (1|sID), data=tdata_sub)

# follow-up analysis 

ls1 <- lsmeans(a1, c("variable", "type_effect")) # joint evaluation (basically gives the same table)
ls1
```


```{r}
############### 
# a conditional analysis 

ls2 <- lsmeans(a1, c("variable"), by = "type_effect") # group means by between-condition
ls2

# simple main effects 
t1 <- pairs(ls2) # compares rep-measure differences separately for each between-factor level
t1
# interaction contrast 
pairs(pairs(ls2), by = NULL)

#test(pairs(pairs(ls2), by = NULL), joint = TRUE) # This reproduces the F-Value of the ANOVA interaction


#lsmip(a1, High_Strength_Component ~ variable) # lsemans can also produce graphs
```
```{r}
confint(t1)
```




```{r}
# compute Cohen's d

library(rstatix)

# subset for the four panels shown in the figure
domains_same <- subset(tdata_sub, type_effect == "same domain")
domains_diff <- subset(tdata_sub, type_effect == "different domains")


d_same <- domains_same %>% cohens_d(value ~ variable, paired = TRUE)
d_same

d_diff <- domains_diff %>% cohens_d(value ~ variable, paired = TRUE)
d_diff

# d overall 

d_over <- tdata_sub %>% cohens_d(value ~ variable, paired = TRUE)
d_over
```



```{r}
# Get CI for overall d 


# get CI for overall effect

# 1) first correlation between strength ratings
cor.test(tdata$single_strength, tdata$multi_strength)

cor <- 0.07451971 



# 2) Now compute SE for d

n <- 60

d_overall <- 0.4213557


# formula: Sqrt((1/n + d^2/n)*2*(1-r))

SEd <- sqrt((1/n + d_overall^2/n)*2*(1-cor))
SEd
```
```{r}
# Confidence intervalls for d

("d overall")
round(d_overall,2)
round((d_overall - 1.96*SEd),2)
round((d_overall + 1.96*SEd),2)
```





